name: deeplearning
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _python_abi3_support=1.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.13.2
  - aiosignal=1.4.0
  - annotated-types=0.6.0
  - anyio=4.12.0
  - appnope=0.1.4
  - arrow-cpp=21.0.0
  - asttokens=3.0.0
  - attrs=25.4.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.4
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.6
  - aws-c-http=0.10.4
  - aws-c-io=0.21.4
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.8.7
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.34.0
  - aws-sdk-cpp=1.11.638
  - backports.zstd=1.2.0
  - blas=1.0
  - bottleneck=1.4.2
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2025.12.2
  - certifi=2025.11.12
  - charset-normalizer=3.4.4
  - colorama=0.4.6
  - comm=0.2.3
  - cpython=3.13.11
  - datasets=4.4.2
  - debugpy=1.8.16
  - decorator=5.2.1
  - dill=0.3.7
  - distro=1.9.0
  - exceptiongroup=1.3.1
  - executing=2.2.1
  - filelock=3.20.1
  - frozenlist=1.7.0
  - fsspec=2025.10.0
  - gflags=2.2.2
  - glog=0.5.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - h11=0.16.0
  - h2=4.3.0
  - hf-xet=1.2.1
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - huggingface_hub=0.36.0
  - hyperframe=6.1.0
  - icu=73.1
  - idna=3.11
  - importlib-metadata=8.7.0
  - ipykernel=6.31.0
  - ipython=9.7.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.8
  - jedi=0.19.2
  - jinja2=3.1.6
  - jiter=0.12.0
  - joblib=1.5.3
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - jupyterlab_widgets=3.0.16
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20250814.1
  - libblas=3.9.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.9.0
  - libcurl=8.17.0
  - libcxx=20.1.8
  - libdeflate=1.22
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.3
  - libffi=3.4.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgrpc=1.74.1
  - libhwloc=2.12.1
  - libiconv=1.16
  - libjpeg-turbo=3.1.2
  - liblapack=3.9.0
  - libllvm20=20.1.8
  - libmpdec=4.0.0
  - libnghttp2=1.67.0
  - libopenblas=0.3.30
  - libpng=1.6.53
  - libprotobuf=6.33.0
  - libre2-11=2025.11.05
  - libsentencepiece=0.2.1
  - libsodium=1.0.20
  - libssh2=1.11.1
  - libthrift=0.22.0
  - libtiff=4.7.0
  - libtorch=2.7.0
  - libuv=1.51.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - llvmlite=0.46.0
  - lz4-c=1.9.4
  - markupsafe=3.0.3
  - matplotlib-inline=0.2.1
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.7.0
  - multiprocess=0.70.15
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.6.1
  - nomkl=1.0
  - numba=0.63.1
  - numexpr=2.14.1
  - numpy=2.3.5
  - numpy-base=2.3.5
  - openai=1.109.1
  - openjpeg=2.5.3
  - openssl=3.6.0
  - opentelemetry-api=1.38.0
  - optree=0.18.0
  - orc=2.2.0
  - packaging=25.0
  - pandas=2.3.3
  - parso=0.8.5
  - pexpect=4.9.0
  - pillow=11.3.0
  - pip=25.3
  - platformdirs=4.5.0
  - prompt-toolkit=3.0.52
  - prompt_toolkit=3.0.52
  - propcache=0.3.1
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow=21.0.0
  - pybind11=3.0.1
  - pybind11-global=3.0.1
  - pydantic=2.12.4
  - pydantic-core=2.41.5
  - pygments=2.19.2
  - pynndescent=0.5.13
  - pysocks=1.7.1
  - python=3.13.11
  - python-dateutil=2.9.0post0
  - python-gil=3.13.11
  - python-tzdata=2025.2
  - python-xxhash=3.6.0
  - python_abi=3.13
  - pytorch=2.7.0
  - pytz=2025.2
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - re2=2025.11.05
  - readline=8.3
  - regex=2025.11.3
  - requests=2.32.5
  - safetensors=0.7.0
  - scikit-learn=1.8.0
  - scipy=1.16.3
  - sentence-transformers=5.2.0
  - sentencepiece=0.2.1
  - sentencepiece-python=0.2.1
  - sentencepiece-spm=0.2.1
  - setuptools=80.9.0
  - six=1.17.0
  - sleef=3.9.0
  - snappy=1.2.2
  - sniffio=1.3.1
  - sqlite=3.51.0
  - stack_data=0.6.3
  - sympy=1.14.0
  - tbb=2022.3.0
  - tenacity=9.1.2
  - threadpoolctl=3.6.0
  - tiktoken=0.12.0
  - tk=8.6.15
  - tokenizers=0.22.2
  - tornado=6.5.4
  - tqdm=4.67.1
  - traitlets=5.14.3
  - transformers=4.57.3
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - tzdata=2025b
  - umap-learn=0.5.9.post2
  - urllib3=2.6.2
  - utf8proc=2.6.1
  - wcwidth=0.2.13
  - wheel=0.45.1
  - widgetsnbextension=4.0.15
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xxhash=0.8.3
  - xz=5.6.4
  - yaml=0.2.5
  - yarl=1.22.0
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstd=1.5.7
prefix: /Applications/anaconda3/envs/deeplearning
