name: deeplearning
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _python_abi3_support=1.0=hd8ed1ab_2
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.2=py313h2082a12_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - annotated-types=0.6.0=py313hca03da5_1
  - anyio=4.12.0=pyhcf101f3_0
  - appnope=0.1.4=py313hca03da5_0
  - arrow-cpp=21.0.0=hc027f7d_2
  - asttokens=3.0.0=py313hca03da5_0
  - attrs=25.4.0=pyhcf101f3_1
  - aws-c-auth=0.9.0=h79febb2_2
  - aws-c-cal=0.9.2=hd08b81e_1
  - aws-c-common=0.12.4=h6caf38d_0
  - aws-c-compression=0.3.1=habbe1e8_6
  - aws-c-event-stream=0.5.6=hd40f934_1
  - aws-c-http=0.10.4=he148155_1
  - aws-c-io=0.21.4=h89d1e94_1
  - aws-c-mqtt=0.13.3=h8d8bef9_4
  - aws-c-s3=0.8.7=h79febb2_0
  - aws-c-sdkutils=0.2.4=habbe1e8_1
  - aws-checksums=0.2.7=habbe1e8_2
  - aws-crt-cpp=0.34.0=hee39554_0
  - aws-sdk-cpp=1.11.638=h35fa3df_0
  - backports.zstd=1.2.0=py313hf42fe89_0
  - blas=1.0=openblas
  - bottleneck=1.4.2=py313h03d0aa3_1
  - brotli-python=1.2.0=py313h5b255a4_0
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.34.6=hc919400_0
  - ca-certificates=2025.12.2=hca03da5_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=py313hca03da5_0
  - cpython=3.13.11=py313hd8ed1ab_100
  - datasets=4.4.2=pyhcf101f3_0
  - debugpy=1.8.16=py313h50f4ffc_1
  - decorator=5.2.1=py313hca03da5_0
  - dill=0.3.7=pyhd8ed1ab_0
  - distro=1.9.0=py313hca03da5_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=py313hca03da5_0
  - filelock=3.20.1=pyhd8ed1ab_0
  - frozenlist=1.7.0=py313hf28abc0_0
  - fsspec=2025.10.0=pyhd8ed1ab_0
  - gflags=2.2.2=hf9b8971_1005
  - glog=0.5.0=h5c6a83d_0
  - gmp=6.3.0=h7bae524_2
  - gmpy2=2.2.1=py313hc1c22ca_2
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hf-xet=1.2.1=py310h6ce4931_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - huggingface_hub=0.36.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.1=h313beb8_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.31.0=py313h7eb115d_0
  - ipython=9.7.0=py313hca03da5_0
  - ipython_pygments_lexers=1.1.1=py313hca03da5_0
  - ipywidgets=8.1.8=pyhd8ed1ab_0
  - jedi=0.19.2=py313hca03da5_0
  - jinja2=3.1.6=pyhcf101f3_1
  - jiter=0.12.0=py313h931abed_0
  - joblib=1.5.3=pyhd8ed1ab_0
  - jupyter_client=8.6.3=py313hca03da5_1
  - jupyter_core=5.9.1=py313hca03da5_0
  - jupyterlab_widgets=3.0.16=pyhcf101f3_1
  - krb5=1.21.3=h237132a_0
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libabseil=20250814.1=cxx17_hbea547f_0
  - libblas=3.9.0=1_h2ec9a88_netlib
  - libbrotlicommon=1.2.0=hbd7815e_0
  - libbrotlidec=1.2.0=h1e834b2_0
  - libbrotlienc=1.2.0=h5439a07_0
  - libcblas=3.9.0=13_hd5b1ab5_netlib
  - libcurl=8.17.0=hdece5d2_1
  - libcxx=20.1.8=hd7fd590_1
  - libdeflate=1.22=hd74edd7_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libevent=2.1.12=h2757513_1
  - libexpat=2.7.3=h50f4ffc_4
  - libffi=3.4.4=hca03da5_1
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgfortran=15.2.0=h09d7db9_1
  - libgfortran5=15.2.0=hb654fa1_1
  - libgrpc=1.74.1=h941cc20_0
  - libhwloc=2.12.1=default_h2915d5d_1000
  - libiconv=1.16=h80987f9_3
  - libjpeg-turbo=3.1.2=hc919400_0
  - liblapack=3.9.0=13_ha522803_netlib
  - libllvm20=20.1.8=h1701f07_0
  - libmpdec=4.0.0=h80987f9_0
  - libnghttp2=1.67.0=hc438710_0
  - libopenblas=0.3.30=hf2bb037_2
  - libpng=1.6.53=hfab5511_0
  - libprotobuf=6.33.0=hff18ee8_0
  - libre2-11=2025.11.05=hd4f4e8d_0
  - libsentencepiece=0.2.1=h5536a6c_0
  - libsodium=1.0.20=h897f8a9_0
  - libssh2=1.11.1=h1590b86_0
  - libthrift=0.22.0=h14a376c_1
  - libtiff=4.7.0=hfce79cd_1
  - libtorch=2.7.0=gpu_mps_h96286cc_201
  - libuv=1.51.0=h6caf38d_1
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.13.9=h528a072_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=20.1.8=he822017_0
  - llvmlite=0.46.0=py313hc8eb11b_0
  - lz4-c=1.9.4=h313beb8_1
  - markupsafe=3.0.3=py313h7d74516_0
  - matplotlib-inline=0.2.1=py313hca03da5_0
  - mpc=1.3.1=h8f1351a_1
  - mpfr=4.2.1=hb693164_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - multidict=6.7.0=py313h92dd972_0
  - multiprocess=0.70.15=py313hca03da5_0
  - ncurses=6.5=hee39554_0
  - nest-asyncio=1.6.0=py313hca03da5_0
  - networkx=3.6.1=pyhcf101f3_0
  - nomkl=1.0=h5ca1d4c_0
  - numba=0.63.1=py313hadc56cb_0
  - numexpr=2.14.1=py313h5fbe615_0
  - numpy=2.3.5=py313h4bb6f22_0
  - numpy-base=2.3.5=py313h23175f9_0
  - openai=1.109.1=py313hca03da5_0
  - openjpeg=2.5.3=h889cd5d_1
  - openssl=3.6.0=h5503f6c_0
  - opentelemetry-api=1.38.0=py313hca03da5_0
  - optree=0.18.0=py313ha61f8ec_0
  - orc=2.2.0=hd6530ca_1
  - packaging=25.0=py313hca03da5_1
  - pandas=2.3.3=py313h3f644e9_1
  - parso=0.8.5=py313hca03da5_0
  - pexpect=4.9.0=py313hca03da5_1
  - pillow=11.3.0=py313he4c6d0d_3
  - pip=25.3=pyhc872135_0
  - platformdirs=4.5.0=py313hca03da5_0
  - prompt-toolkit=3.0.52=py313hca03da5_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - propcache=0.3.1=py313ha9b7d5b_0
  - psutil=7.0.0=py313haa24f5a_1
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd3eb1b0_3
  - pure_eval=0.2.3=py313hca03da5_0
  - pyarrow=21.0.0=py313h3f644e9_1
  - pybind11=3.0.1=pyh7a1b43c_0
  - pybind11-global=3.0.1=pyhc7ab6ef_0
  - pydantic=2.12.4=py313hca03da5_0
  - pydantic-core=2.41.5=py313h931abed_1
  - pygments=2.19.2=py313hca03da5_0
  - pynndescent=0.5.13=py313hca03da5_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.13.11=hc7d8306_100_cp313
  - python-dateutil=2.9.0post0=py313hca03da5_2
  - python-gil=3.13.11=h4df99d1_100
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python-xxhash=3.6.0=py313hee11f83_1
  - python_abi=3.13=3_cp313
  - pytorch=2.7.0=gpu_mps_py313h1211112_201
  - pytz=2025.2=py313hca03da5_0
  - pyyaml=6.0.3=py313h7d74516_0
  - pyzmq=27.1.0=py313h5a8c52c_1
  - re2=2025.11.05=h1413154_0
  - readline=8.3=h0b18652_0
  - regex=2025.11.3=py313h6535dbc_1
  - requests=2.32.5=pyhd8ed1ab_0
  - safetensors=0.7.0=py313h0b74987_0
  - scikit-learn=1.8.0=py313h003a250_0
  - scipy=1.16.3=py313h29d7d31_2
  - sentence-transformers=5.2.0=pyhd8ed1ab_0
  - sentencepiece=0.2.1=py313h90623b3_0
  - sentencepiece-python=0.2.1=py313hd91b786_0
  - sentencepiece-spm=0.2.1=h5536a6c_0
  - setuptools=80.9.0=py313hca03da5_0
  - six=1.17.0=py313hca03da5_0
  - sleef=3.9.0=hb028509_0
  - snappy=1.2.2=hada39a4_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - sqlite=3.51.0=hab6afd1_0
  - stack_data=0.6.3=py313hca03da5_0
  - sympy=1.14.0=pyh2585a3b_105
  - tbb=2022.3.0=h50665e7_0
  - tenacity=9.1.2=py313hca03da5_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tiktoken=0.12.0=py313h4bd1e59_2
  - tk=8.6.15=hcd8a7d5_0
  - tokenizers=0.22.2=py313h4bd1e59_0
  - tornado=6.5.4=py313haa24f5a_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=py313hca03da5_0
  - transformers=4.57.3=pyhd8ed1ab_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=py313hca03da5_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - umap-learn=0.5.9.post2=py313h8f79df9_1
  - urllib3=2.6.2=pyhd8ed1ab_0
  - utf8proc=2.6.1=h80987f9_1
  - wcwidth=0.2.13=py313hca03da5_0
  - wheel=0.45.1=py313hca03da5_0
  - widgetsnbextension=4.0.15=pyhd8ed1ab_0
  - xorg-libxau=1.0.12=hc919400_1
  - xorg-libxdmcp=1.1.5=hc919400_1
  - xxhash=0.8.3=haa4e116_0
  - xz=5.6.4=h80987f9_1
  - yaml=0.2.5=h925e9cb_3
  - yarl=1.22.0=py313h7d74516_0
  - zeromq=4.3.5=h2c7f8f0_1
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h817c040_0
prefix: /Applications/anaconda3/envs/deeplearning
